// <auto-generated />
using System;
using LabIQ.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabIQ.Api.Migrations
{
    [DbContext(typeof(LabIqDbContext))]
    [Migration("20260603212131_AddTestOrdersAndTransportChannels")]
    partial class AddTestOrdersAndTransportChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("LabIQ.Api.Domain.AuditEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterStateHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeStateHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.InboundFileAcknowledgment", b =>
                {
                    b.Property<int>("AckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedByIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AckId");

                    b.HasIndex("ChannelId");

                    b.ToTable("InboundFileAcknowledgments");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccreditationBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccreditationNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabCompanyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLims")
                        .HasColumnType("TEXT");

                    b.HasKey("LabId");

                    b.HasIndex("LabCompanyCode")
                        .IsUnique();

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.LabLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabLocationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.HasIndex("LabId", "LabLocationCode")
                        .IsUnique();

                    b.ToTable("LabLocations");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.LocationTestAvailability", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestCodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId", "TestCodeId");

                    b.HasIndex("TestCodeId");

                    b.ToTable("LocationTestAvailabilities");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.ParameterCode", b =>
                {
                    b.Property<int>("ParameterCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultResultType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ParameterCodeId");

                    b.HasIndex("LabId", "Code")
                        .IsUnique();

                    b.ToTable("ParameterCodes");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.ParameterDescription", b =>
                {
                    b.Property<int>("ParameterDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterCodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParameterDescriptionId");

                    b.HasIndex("ParameterCodeId");

                    b.ToTable("ParameterDescriptions");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestCode", b =>
                {
                    b.Property<int>("TestCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matrix")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("TestCodeId");

                    b.HasIndex("LabId", "Code")
                        .IsUnique();

                    b.ToTable("TestCodes");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestDescription", b =>
                {
                    b.Property<int>("TestDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestCodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestDescriptionId");

                    b.HasIndex("TestCodeId");

                    b.ToTable("TestDescriptions");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestOrder", b =>
                {
                    b.Property<int>("TestOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SureTrendOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TestOrderId");

                    b.HasIndex("LocationId");

                    b.ToTable("TestOrders");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestParameterAssociation", b =>
                {
                    b.Property<int>("TestCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterCodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestCodeId", "ParameterCodeId");

                    b.HasIndex("ParameterCodeId");

                    b.ToTable("TestParameterAssociations");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnalyteCodesMatch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BoundAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSampleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabSampleCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("TestResultId");

                    b.HasIndex("TestOrderId")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TransportChannel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNamingTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostingMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("InboxPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutboxPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.HasIndex("LocationId", "ChannelType")
                        .IsUnique();

                    b.ToTable("TransportChannels");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.InboundFileAcknowledgment", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.TransportChannel", "Channel")
                        .WithMany("Acknowledgments")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.LabLocation", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.Lab", "Lab")
                        .WithMany("Locations")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.LocationTestAvailability", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.LabLocation", "Location")
                        .WithMany("TestAvailability")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabIQ.Api.Domain.TestCode", "TestCode")
                        .WithMany()
                        .HasForeignKey("TestCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.ParameterCode", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.Lab", "Lab")
                        .WithMany("ParameterCodes")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.ParameterDescription", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.ParameterCode", "ParameterCode")
                        .WithMany("Descriptions")
                        .HasForeignKey("ParameterCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParameterCode");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestCode", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.Lab", "Lab")
                        .WithMany("TestCodes")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestDescription", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.TestCode", "TestCode")
                        .WithMany("Descriptions")
                        .HasForeignKey("TestCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestOrder", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.LabLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestParameterAssociation", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.ParameterCode", "ParameterCode")
                        .WithMany("TestAssociations")
                        .HasForeignKey("ParameterCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabIQ.Api.Domain.TestCode", "TestCode")
                        .WithMany("ParameterAssociations")
                        .HasForeignKey("TestCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParameterCode");

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestResult", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.TestOrder", "TestOrder")
                        .WithOne("Result")
                        .HasForeignKey("LabIQ.Api.Domain.TestResult", "TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TransportChannel", b =>
                {
                    b.HasOne("LabIQ.Api.Domain.LabLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.Lab", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("ParameterCodes");

                    b.Navigation("TestCodes");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.LabLocation", b =>
                {
                    b.Navigation("TestAvailability");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.ParameterCode", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("TestAssociations");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestCode", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("ParameterAssociations");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TestOrder", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("LabIQ.Api.Domain.TransportChannel", b =>
                {
                    b.Navigation("Acknowledgments");
                });
#pragma warning restore 612, 618
        }
    }
}
